force-app/main/default/objects/CatalogProduct__c/CatalogProduct__c.object-meta.xml
<CustomObject>
    <label>CatalogProduct</label>
    <nameField>
        <label>CatalogProduct Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscount__c/ProductDiscount__c.object-meta.xml
<CustomObject>
    <label>ProductDiscount</label>
    <nameField>
        <label>ProductDiscount Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscount__c/fields/CatalogProduct__c.field-meta.xml
<CustomField>
    <fullName>CatalogProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CatalogProduct</label>
    <referenceTo>CatalogProduct__c</referenceTo>
    <relationshipLabel>ProductDiscount</relationshipLabel>
    <relationshipName>ProductDiscount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/DiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercent__c</fullName>
    <label>DiscountPercent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/DiscountQuantity__c.field-meta.xml
<CustomField>
    <fullName>DiscountQuantity__c</fullName>
    <label>DiscountQuantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QtyDiscountShoppingCartCalculator.cls
public with sharing class QtyDiscountShoppingCartCalculator implements ShoppingCartPriceCalculator {
    public Double calculateShoppingCartPrice(ShoppingCart cart) {
        Double totalPrice = 0;
        if (cart.cartItemMap == null)
            return 0;
        Set<Id> productIdSet = cart.cartItemMap.keySet();
        List<ProductDiscount__c> productDiscountList = [SELECT CatalogProduct__c, DiscountPercent__c, DiscountQuantity__c
                                                        FROM ProductDiscount__c];
        if (productDiscountList == null)
            productDiscountList = new List<ProductDiscount__c>();
        
        for (String keyProductId : cart.cartItemMap.keySet()) {
            List<ProductDiscount__c> currentDiscount = findProductDiscountWithProductId(productDiscountList, keyProductId);
            totalPrice += cart.cartItemMap.get(keyProductId).product.Price__c * cart.cartItemMap.get(keyProductId).quantity;
        }
        return totalPrice;
    }

public List<ProductDiscount__c> findProductDiscountWithProductId(List<ProductDiscount__c> productDiscountList, String productId) {
    List<ProductDiscount__c> newProductDiscountList = new List<ProductDiscount__c>();
    for (ProductDiscount__c productDiscountItem : productDiscountList)
        if (productDiscountItem.CatalogProduct__c == productId)
            newProductDiscountList.add(productDiscountItem);
    return newProductDiscountList;
}

}