force-app/main/default/objects/CatalogProduct__c/CatalogProduct__c.object-meta.xml
<CustomObject>
    <label>CatalogProduct</label>
    <nameField>
        <label>CatalogProduct Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscount__c/ProductDiscount__c.object-meta.xml
<CustomObject>
    <label>ProductDiscount</label>
    <nameField>
        <label>ProductDiscount Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscount__c/fields/CatalogProduct__c.field-meta.xml
<CustomField>
    <fullName>CatalogProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CatalogProduct</label>
    <referenceTo>CatalogProduct__c</referenceTo>
    <relationshipLabel>ProductDiscount</relationshipLabel>
    <relationshipName>ProductDiscount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/DiscountQuantity__c.field-meta.xml
<CustomField>
    <fullName>DiscountQuantity__c</fullName>
    <label>DiscountQuantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Utility.cls
public class Utility {
    public static ProductDiscount__c findProductDiscountWithProductIdAndQuantity(List<ProductDiscount__c> productDiscountList, String productId, Integer currentQty) {
        if (productDiscountList == null)
            return null;
        ProductDiscount__c discountFound = null;
        for (ProductDiscount__c productDiscountItem : productDiscountList) {
            if (productDiscountItem.CatalogProduct__c == productId) {
                if (productDiscountItem.DiscountQuantity__c == currentQty)
                    return productDiscountItem;
                List<Integer> multipleList = findMultiples(currentQty);
                if (multipleList.contains(Integer.valueOf(productDiscountItem.DiscountQuantity__c)))
                    return productDiscountItem;
            }
        }
        return discountFound;
    }

    public static List<Integer> findMultiples(Integer numberToDecompose) {
        List<Integer> multipleList = new List<Integer>();
        for (Integer i = numberToDecompose; i > 0; i--)
            if (Math.mod(numberToDecompose, i) == 0)
                multipleList.add(i);
        return multipleList;
    }
}